import { z } from "zod"

import { HousingMatch, UserProfile } from "@/domain"

// A HousingMatch with the agent's own ranking judgment attached. score /
// scoreBreakdown on HousingMatch are reserved for this — rationale is a
// plain-language version of the same judgment, generated by the model
// rather than computed by a formula. rentUsd/bedrooms are pulled from
// getHousingDetail and echoed here so the UI can render pricing without
// re-parsing it out of the model's prose.
export const rankedHousingMatchSchema = HousingMatch.extend({
  rentUsd: z.number().optional(),
  bedrooms: z.number().optional(),
  rentToIncomeRatio: z.number().optional(),
  rationale: z.string(),
})
export type RankedHousingMatch = z.infer<typeof rankedHousingMatchSchema>

export const showMapInputSchema = z.object({
  profile: UserProfile,
  matches: z.array(rankedHousingMatchSchema),
})
export type ShowMapInput = z.infer<typeof showMapInputSchema>

export const amiTierSchema = z.enum([
  "extremely-low",
  "very-low",
  "low",
  "above-low-income",
])
export type AmiTier = z.infer<typeof amiTierSchema>
